#!/usr/bin/env bash

# Generates THIRD-PARTY-LICENSES.md for the gotiler executable, reproducing the
# licenses and notices of everything it embeds:
#
#   1. the Go standard library and runtime;
#   2. every Go module linked into ./cmd for the target platform (GOOS/GOARCH),
#      read from the module cache, including license files of vendored code
#      nested inside a module (e.g. klauspost/compress/zstd/internal/xxhash);
#   3. native libraries passed with --notice (PROJ, SQLite, libtiff, ...);
#   4. the embedded data and ported code listed in scripts/third-party-notices.md.
#
# The Docker build runs it for every target, passing the licenses of the
# statically linked C libraries, and ships the result in the release archives.

set -o errexit
set -o nounset
set -o pipefail

usage() {
    cat <<'EOF'
Usage: scripts/3p-license-gen.sh [--out FILE] [--notice "NAME=FILE"]...

Options:
  --out FILE            Output file (default: THIRD-PARTY-LICENSES.md in the
                        repository root)
  --notice "NAME=FILE"  Append the license file FILE under the heading NAME.
                        Repeatable; used for statically linked native libraries.
  -h, --help            Show this help

The target platform follows GOOS/GOARCH, like go build.
EOF
}

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$repo_root/THIRD-PARTY-LICENSES.md"
notices=()

while [[ $# -gt 0 ]]; do
    case "$1" in
        --out)
            out="$2"
            shift 2
            ;;
        --notice)
            notices+=("$2")
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument: $1" >&2
            usage >&2
            exit 1
            ;;
    esac
done

cd "$repo_root"

# normalize Windows paths (as printed by go list on Windows) to forward slashes
slashes() {
    printf '%s' "${1//\\//}"
}

# license_files DIR prints the license and notice files found directly in DIR,
# including third-party notice files of code the module itself derives from
license_files() {
    find "$1" -maxdepth 1 -type f ! -iname '*.go' \( -iname 'LICENSE*' -o -iname 'LICENCE*' -o -iname 'COPYING*' -o -iname 'NOTICE*' -o -iname '*THIRD*PARTY*' \) | sort
}

# fenced FILE prints FILE inside a code fence; four backticks keep license
# texts that contain markdown fences intact
fenced() {
    printf '````text\n'
    tr -d '\r' < "$1"
    printf '\n````\n'
}

section() {
    printf '\n---\n\n## %s\n\n' "$1"
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

goos="$(go env GOOS)"
goarch="$(go env GOARCH)"

{
    printf '# Third-Party Licenses\n\n'
    printf 'The gotiler executable is released under the GNU Affero General Public License v3\n'
    printf '(see LICENSE.md). It embeds the third-party components listed below, whose\n'
    printf 'licenses and notices are reproduced in full.\n\n'
    printf 'Generated by `scripts/3p-license-gen.sh` for %s/%s.\n' "$goos" "$goarch"

    section "Go standard library and runtime ($(go env GOVERSION))"
    fenced "$(slashes "$(go env GOROOT)")/LICENSE"
} > "$tmp"

# Every package linked into the executable, with its module. The module root
# license always applies; a package can additionally sit below a nested license
# file (vendored code), found walking up from the package to the module root.
declare -A module_version module_files
while IFS=$'\t' read -r pkg_dir mod_path mod_version mod_dir; do
    pkg_dir="$(slashes "$pkg_dir")"
    mod_dir="$(slashes "$mod_dir")"
    if [[ -z "$mod_dir" ]]; then
        echo "Module $mod_path is not in the module cache: run go mod download first" >&2
        exit 1
    fi
    module_version["$mod_path"]="$mod_version"
    files="$(license_files "$mod_dir")"
    dir="$pkg_dir"
    while [[ "$dir" == "$mod_dir"/* ]]; do
        nested="$(license_files "$dir")"
        if [[ -n "$nested" ]]; then
            files+=$'\n'"$nested"
            break
        fi
        dir="$(dirname "$dir")"
    done
    module_files["$mod_path"]+=$'\n'"$files"
done < <(go list -deps -f '{{with .Module}}{{if not .Main}}{{$.Dir}}{{"\t"}}{{.Path}}{{"\t"}}{{.Version}}{{"\t"}}{{.Dir}}{{end}}{{end}}' ./cmd)

while read -r mod_path; do
    [[ -n "$mod_path" ]] || continue
    files="$(printf '%s\n' "${module_files[$mod_path]}" | sed '/^$/d' | sort -u)"
    if [[ -z "$files" ]]; then
        echo "No license file found for module $mod_path" >&2
        exit 1
    fi
    mod_dir_prefix="$(go list -m -f '{{.Dir}}' "$mod_path")"
    mod_dir_prefix="$(slashes "$mod_dir_prefix")/"
    {
        section "$mod_path ${module_version[$mod_path]}"
        while read -r f; do
            printf '%s:\n\n' "${f#"$mod_dir_prefix"}"
            fenced "$f"
            printf '\n'
        done <<< "$files"
    } >> "$tmp"
done < <(printf '%s\n' "${!module_version[@]}" | sort)

for notice in "${notices[@]}"; do
    name="${notice%%=*}"
    file="${notice#*=}"
    if [[ ! -f "$file" ]]; then
        echo "Notice file for $name not found: $file" >&2
        exit 1
    fi
    {
        section "$name"
        fenced "$file"
    } >> "$tmp"
done

{
    printf '\n---\n\n'
    tr -d '\r' < "$repo_root/scripts/third-party-notices.md"
} >> "$tmp"

mkdir -p "$(dirname "$out")"
mv "$tmp" "$out"
trap - EXIT
echo "Wrote $out"
